[project]
name = "ai-appointment-booking-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Walid Khan", email = "swatwalid4142@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ai-appointment-booking-agent = "ai_appointment_booking_agent:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
